### ISSUE TITLE
Surge XT Wavetable VCO pitch ctrl. attenuates amplitude

### ISSUE THREAD

**Issue by jocphx** [surge-synthesizer/surge-rack#1015] opened 2024-08-09 22:17 UTC
The other day I was attempting to use Surge XT’s Wavetable VCO as a LFO. The wavetable loaded was the default “Sine HQ”. As I set the octave to -3 and moved the pitch knob to its minimum, I noticed that besides the pitch, both Octave and Pitch are interfering with the amplitude of the signal.

This can be easily seen by connecting a Scope and see the signal fade as the pitch gets lower.

I gave a quick check to a few of the other VCOs of this collection, and it seems that the effect is less noticeable but it is still there.

I ended up using a different module in my patch because of this issue.

Can someone please have a look?
![Yr7VzAu](https://github.com/user-attachments/assets/d47f3746-2ce2-49f1-bfb2-f7aa8ae4143a)

**Comment by baconpaul** [comment] 2024-08-10 12:54
These algorithms really don’t work at super low amplitudes. If you want the amplitude that low I’d suggest modern (or one of the lfos). 

The situation may improve with a higher density wavetable also. What I suspect is happening is the wavetable doesn’t have enough impulses at super low frequencies 

probably nothing to fix here though

**Comment by Petervos2018** [comment] 2024-08-10 13:10
` at super low amplitudes. If you want the amplitude that low I’d suggest modern`

Where you say amplitudes you mean frequencies I presume ? It's the amplitude that is going down with the frequencies that is what this post is about.

**Comment by Petervos2018** [comment] 2024-08-10 13:19
Here is VCO modern it also dips when the freq is extremely low.

https://i.imgur.com/5VbpJQH.gif

**Comment by Andreya-Autumn** [comment] 2024-08-10 15:03
You almost definitely need to uncheck "apply DC blocker" in the right click menu of both. That might help a bit. 

But indeed, Paul meant frequencies. Our WT VCO is not a great fit for LFO duties for a few reasons. I would think the Modern VCO should work fine though so probably it's the DC filter.

**Comment by Andreya-Autumn** [comment] 2024-08-10 15:14
Yeah just confirmed, on the Modern VCO just uncheck the DC filter and it will play low freqs at full amplitude. 

The Wavetable VCO on the other hand has DC-blocker-like behavior in the oscillator algo itself. So do the Classic and S&H Noise ones, for the reciord. That's very non-trivial to change, and not the intended use case, so indeed nothing to fix here. So closing the issue. Feel free to reopen if there's something I've missed.

**Closed by Andreya-Autumn** 2024-08-10 15:14 UTC

**Comment by Petervos2018** [comment] 2024-08-10 15:31
Thanks for answering, all clear to me now.

Greetings Peter.

**Comment by baconpaul** [comment] 2024-08-10 16:11
And yes I meant frequencies of course!

thanks!

**Comment by jocphx** [comment] 2024-08-10 21:55
@baconpaul I'm sorry, but I see that different waves behave differently, in this respect. Like each waveform has a different sampling... Please let me understand... Simple waveforms suffer the most compared to "octaves", or more complex waves. If the sampling frequency was the same for all the waves, shouldn't we see the same issue across all wave-shapes? Again, I'm ignorant, and I'd like to understand...

**Comment by Andreya-Autumn** [comment] 2024-08-10 22:38
That difference is also expected I'm afraid. The reason for is is due to the method used to generate the an audio rate waveform from the wavetables, which seeks to eliminate the inharmonic aliasing which is often considered the main flaw of digital oscillators. It works well in that respect but there are some tradeoffs. One of which is the one you're seeing now. 

We're being a bit handwavy about it because the real answer is a little bit math-heavy. But the gist of it is, it tries to build a smooth bridge between the samples in the wavetable, and when those happen too rarely  the model fails to reliably produce the desired output. Hence the DC-blocker-ish behavior I mentioned. If you load a square wavetable you'll see it basically just outputs the up and down pulses, sort of like a DC-filtered square wave would. It does do a little better on waves with a lot of activity indeed. But yeah, long story short it's not the best choice for an LFO algorithm indeed, and changing that fact isn't easy.

**Comment by Andreya-Autumn** [comment] 2024-08-10 22:41
If you do wanna read more about the maths the method is documented in the Classic oscillator code: https://github.com/surge-synthesizer/surge/blob/main/src/common/dsp/oscillators/ClassicOscillator.cpp

**Comment by baconpaul** [comment] 2024-08-11 10:58
The wavetable density will also matter. If the frame size is small vs large that will change the nature of the generstor at very low frequencies

**Comment by Andreya-Autumn** [comment] 2024-08-11 14:42
Oh by the way, @jocphx I just realized we've both neglected to (explicitly) give you a piece of information I'm sure you really want: The Window VCO plays all the same wavetables, but uses different maths to render the wave, which deals with low frequencies way better.  
![Check it out](https://github.com/user-attachments/assets/bc1812dd-d12c-4efd-845d-3380d9f8e07b)

Turn off the DC blocker in the menu, and put it in rectangle mode (effectively the same as disabling the windowing) and it works alright. You don't get all the same parameters you get in the WT VCO, but you can get similar results in rack anyway with things liks self-FM or waveshaping.

**Comment by jocphx** [comment] 2024-08-11 14:56
@Andreya-Autumn @baconpaul  Thank you so much for your explanation and patience!
