### ISSUE TITLE
Delay module: optional clip and l to l/mon

### ISSUE THREAD

**Issue by docb** [surge-synthesizer/surge-rack#777] opened 2023-01-02 13:41 UTC
when providing a normal -5/5V signal at the inputs of the Delay module the delay signal overdrives at low feedback values (starting at 25%). To compare, the same signal passed to RPJ Stereo delay does not overdrive.
With cross feedback it is even worse. The requires to pass a very low gained signals into the input and then amplify it afterwards. This may be not intended.

btw. normaling the right channel to the left also would be great.

**Comment by baconpaul** [comment] 2023-01-02 13:46
https://github.com/surge-synthesizer/surge-rack/blob/83593dfe9e1074ac5e44552a759d3ad06785525a/src/Delay.h#L280

You can see the clipper there yeah. 

I wonder if we need a different set of normalizations available as options indeed.  With feedback at 100% you are right that will run into the clipper in many cases.

what do you mean by r normalized by l?

**Comment by docb** [comment] 2023-01-02 15:37
well it seems to run into the clipper with a normal signal and 25% feedback.
it also seems that the lines above make a hard clip. 
https://github.com/surge-synthesizer/surge-rack/blob/83593dfe9e1074ac5e44552a759d3ad06785525a/src/Delay.h#L276

> what do you mean by r normalized by l?

if the right input is not connected the left input should be taken for the right channel.
currently if only the left input is connected the right output is zero. so one must always connect left and right for a mono signal which should be made stereo with the delay - which is a frequent usecase.

**Comment by docb** [comment] 2023-01-02 15:43
Btw:
It works perfectly when not using any clipping at all:
```
       //auto dl = std::clamp(lineL->read(tl), -1.5f, 1.5f);
        //auto dr = std::clamp(lineR->read(tr), -1.5f, 1.5f);

        // softclip
        //dl = dl - 4.0 / 27.0 * dl * dl * dl;
        //dr = dr - 4.0 / 27.0 * dr * dr * dr;

        auto dl=lineL->read(tl);
        auto dr=lineR->read(tr);
```

**Comment by baconpaul** [comment] 2023-01-02 16:07
Yeah I should make the clipping optional. That’s a good idea. 

The problem is you can make it run away if you set both feedbacks to 100% which is why that is there (and why it is in surge also)

oh and sure make l into l/mon at the input gotcha. That’s easy enough

**Comment by baconpaul** [comment] 2023-01-02 16:07
Oh and the hardclip is because that soft lip form is only valid in -1.5 to 1.5 then pushes that into -1,1 so it looks like a hardclip but it’s really just the ends of the softclip function

**Comment by baconpaul** [comment] 2023-01-02 16:08
Anyway I renamed the issue and will add those features to the 2.1 release!

**Comment by docb** [comment] 2023-01-02 19:39
Thx!

**Comment by baconpaul** [comment] 2023-01-02 21:20
So it seems we want three modes

- transparent (might explode)
- Clip feedback path only (so write in + clip(fb))
- Clip write line (clip(in+fb))

the third is what we do now. I will change default on new instances to second since it guarantees a transparent delay in no feedback case. 

Then it seems we want three clippers 

- softclip at 7.5 to 5v (current mode)
- Softclip same to 7.5v
- Softclip same to 10v

And I will keep the current default 

I am reticent to have the default be no clip in the feedback path since it can easily give runaway feedback 

I’ll code it up this week - it’s all easy changes to the code obviously - so any feedback welcome

**Comment by baconpaul** [comment] 2023-01-02 21:23
We might also want a hardclip 10v at the output of in transparent mode

**Comment by baconpaul** [comment] 2023-01-02 21:24
Or just to place the clipper at the output stage as ppposed to feedback stage overall

**Comment by baconpaul** [comment] 2023-01-02 21:28
Finally we might want a transparent scaled mode where what we write to the delay line is (in + f * l + c * r)/(1+f+c)

**Comment by docb** [comment] 2023-01-03 05:28
well, don't know. in either way as a user i have to ensure to have ok values for feedback. i find it more annoying to adjust because there is potentially overdrive which i may not hear immediately.
it is easier to see a blow up. so when i connect the Autinn NON behind the delay it is completely sufficient and i need this only if i experiment with high feedback values. So in my view a optional limiter (default on) on the output is sufficient.

**Comment by baconpaul** [comment] 2023-01-03 15:23
Yup transparent with output hardclip should clearly be one of the modes. 

Will get these in and push a nightly for your feedback in the next week or so

thanks so much!

**Comment by baconpaul** [comment] 2023-01-04 14:35
OK my next merge will have (1) L/Mon behavior (thanks) and (2) a variety of clipping models in the RMB, with the current surge default still as the default. The mode you want is "Transparent (Potentially Unbounded)" or perhaps "Hardclip Output @10V" which are both transparent delays one with a hard limiter.

Should be there once I merge #783. I'll leave this issue open until you try it though in case you have other thoughts, but mark it resolved.

THanks

**Comment by docb** [comment] 2023-01-04 15:36
I have tested all options:
Input: a signal ranging from -5V to 5V
Feedback 37%, Cross feedback 18%

Transparent: Clean output in range -5.5/5.5V
Softclip Feedback => overdrive
Softclip Input + Feedback => overdrive (identical)
Softclip Out => overdrive (identical)
HardClip 10V => Clean output

So its ok for me. 
However i still don't understand the usecase for the softclip options but may be i don't need to ...

**Comment by baconpaul** [comment] 2023-01-04 15:45
(This is yet another example - albeit on a micro level - of the difference between instrument design and module design. Surge vst has a nicely managed signal path throughout but the choices that amount from that don’t make as much sense standalone. So appreciate you pushing on this)

**Comment by baconpaul** [comment] 2023-01-04 16:15
OK my next push will have three modes: Nothing (potentially runaway), Softclip delay line @5V (the surge VST default); Hardclip delay line @10v (basically runaways -> square wave noise). And I made the third the new default.

Even though that's a change in sound which we need to flag in changelog 2.1, looking at a full height sin in the scope convinces me you are right that hard@10 is the correct rack default.

Thanks for your attention here! Appreciated.

**Comment by docb** [comment] 2023-01-04 20:09
i have tried in the hardclip 10V variant instead of clamp: 
```
dl = std::tanh(dl/2.f)*2; // 10V
dr = std::tanh(dr/2.f)*2;
```
but the difference is imho not very significant and i will take a bit more cpu. 
may be you can give a try.

**Comment by baconpaul** [comment] 2023-01-04 20:23
you mean, make it a soft clip :)

I am happy to add a soft clip 10v version as well as a hard clip version. TANH vs the cubic is not really very different but I can add the 10v cubic version also as a soft clip option

there's that cubic form if you are interested. Saves you a bucket of CPU when you need to do a soft clip.

https://www.desmos.com/calculator/tdaxvoq2w2

**Comment by docb** [comment] 2023-01-04 20:27
yes but then you still have to hardclip to 1.5 -- not sure if this makes it better as pure hardclipping, anyway even with tanh i could not hear some significant better

**Comment by baconpaul** [comment] 2023-01-04 20:28
No you don't. To make the range +/-2 you hardclip to 3.

https://www.desmos.com/calculator/aofya9jlil

take a look there and you'll see!

**Comment by docb** [comment] 2023-01-04 20:30
yes but at the end this is the same thing. i have transferred it to the range of -1,1

**Comment by baconpaul** [comment] 2023-01-04 20:37
yeah exactly. we are saying the same thing.

softclip and hardclip are both options. scale them to 5v or 10v

Here's a 10V signal piped into the delay with the clipper set at a 5v soft, 10v soft and 10v hard.

<img width="1097" alt="Screen Shot 2023-01-04 at 3 35 57 PM" src="https://user-images.githubusercontent.com/13387561/210645203-76012c3e-c4de-4f3e-9717-5d5424181b2a.png">

And here's the same thing with a 5v signal.

<img width="1103" alt="Screen Shot 2023-01-04 at 3 36 07 PM" src="https://user-images.githubusercontent.com/13387561/210645280-a4aa1f14-e765-47f6-965c-e3fe83f5fee3.png">

The cubic is just a faster approximation of tanh is all.

**Comment by baconpaul** [comment] 2023-01-04 20:38
oh and you can see the 10v soft and 10v hard are both equivalently transparent on a 5v signal.

**Comment by docb** [comment] 2023-01-04 21:14
From my side it is fully OK now, the soft clip sounds more pleasant in the case of putting cross feedback to 100%.

**Comment by baconpaul** [comment] 2023-01-04 21:20
Yeah it sounds way better at the cost of transparency at the edges (when you go over the 5v threshold) 

But appreciate the testing and feedback! I’ll close this now

**Closed by baconpaul** 2023-01-04 21:20 UTC
Labels: FX, Resolved Awaiting User Confirm
