### ISSUE TITLE
make install fails for fresh v2.1.1.0

### ISSUE THREAD

**Issue by davidvivier** [surge-synthesizer/surge-rack#827] opened 2023-01-31 16:13 UTC
Hi, i'm trying to build and install from the latest version which is 3 hours old ; not sure if that's specific to that version.

The first steps go fine ; `make install` fails with : 
```
[ 78%] Building CXX object surge/src/common/CMakeFiles/surge-common.dir/dsp/modulators/MSEGModulationHelper.cpp.o
/home/dave/Rack/plugins/surge-rack/surge/src/common/dsp/modulators/MSEGModulationHelper.cpp: In function ‘void Surge::MSEG::extendTo(MSEGStorage*, float, float)’:
/home/dave/Rack/plugins/surge-rack/surge/src/common/dsp/modulators/MSEGModulationHelper.cpp:840:5: error: assuming signed overflow does not occur when assuming that (X + c) >= X is always true [-Werror=strict-overflow]
     if (nxt >= ms->n_activeSegments)
     ^~
At global scope:
cc1plus: error: unrecognized command line option ‘-Wno-class-memaccess’ [-Werror]
cc1plus: error: unrecognized command line option ‘-Wno-stringop-truncation’ [-Werror]
cc1plus: error: unrecognized command line option ‘-Wno-range-loop-construct’ [-Werror]
cc1plus: all warnings being treated as errors
```

using cmake 3.25.1 on Linux Mint (`Linux 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`)

**Comment by baconpaul** [comment] 2023-01-31 16:18
What compiler are you using? It looks like it doesn’t understand our flags.

**Comment by baconpaul** [comment] 2023-01-31 16:19
Anyway it looks like for whatever compiler you are using you need to add the no error for that warning. Or use the compilers the toolchain uses.

**Comment by davidvivier** [comment] 2023-01-31 20:51
Thanks for the hint! Indeed i was using an outdated version of gcc ; i'm now using gcc 12.2 and it compiles better, until 92%.

I now get a bunch of errors or redefinitions, which start with : 
```
[ 92%] Building CXX object CMakeFiles/plugin.dir/src/Mixer.cpp.o
In file included from /home/dave/Rack/dep/include/simde/x86/ssse3.h:30,
                 from /home/dave/Rack/dep/include/simde/x86/sse4.1.h:31,
                 from /home/dave/Rack/dep/include/simde/x86/sse4.2.h:31,
                 from /home/dave/Rack/include/simd/common.hpp:7,
                 from /home/dave/Rack/include/simd/Vector.hpp:3,
                 from /home/dave/Rack/include/simd/functions.hpp:2,
                 from /home/dave/Rack/include/dsp/common.hpp:4,
                 from /home/dave/Rack/include/rack.hpp:110,
                 from /home/dave/Rack/plugins/surge-rack/src/SurgeXT.h:18,
                 from /home/dave/Rack/plugins/surge-rack/src/FX.h:19,
                 from /home/dave/Rack/plugins/surge-rack/src/FX.cpp:16:
/home/dave/Rack/dep/include/simde/x86/sse3.h:297:31: error: redefinition of ‘__m128 simde_mm_addsub_ps(__m128, __m128)’
  297 | #  define _mm_addsub_ps(a, b) simde_mm_addsub_ps(a, b)
      |                               ^~~~~~~~~~~~~~~~~~
/home/dave/Rack/dep/include/simde/x86/sse3.h:271:1: note: ‘simde__m128 simde_mm_addsub_ps(simde__m128, simde__m128)’ previously defined here
  271 | simde_mm_addsub_ps (simde__m128 a, simde__m128 b) {
      | ^~~~~~~~~~~~~~~~~~
/home/dave/Rack/dep/include/simde/x86/sse3.h:330:29: error: redefinition of ‘__m128 simde_mm_hadd_ps(__m128, __m128)’
  330 | #  define _mm_hadd_ps(a, b) simde_mm_hadd_ps(a, b)
...
```

I ran `make clean` before `cmake` ; and the Rack directory i provided seems to be correct (because `include/rack.hpp` is found), i don't understand why a bunch of stuff gets redeclared. But looking at it, those seems to not be linked to surge-rack.

**Comment by baconpaul** [comment] 2023-01-31 21:42
Sigh, the rack condition for x86 isn’t consistent in gcc outside the toolchain. There’s a fix to this we backed down because the toolchain got fixed but can you try something? At the very top of fx.cpp before it includes anything include immintrin

**Comment by baconpaul** [comment] 2023-01-31 21:46
Ahh no the problem is slightly different

https://github.com/VCVRack/Rack/blob/43cc6d02ff761f78a43d2a54c0dc8a46a44a50de/include/simd/common.hpp#L3

seems sse 4 2 isn’t defined. Harumph. 

Lemme see if I can look why. @qno think we might be missing a flag somewhere?

**Comment by baconpaul** [comment] 2023-01-31 22:31
OK so I set up our pipeline to do an out-of-toolchain build on ubuntu-latest

https://github.com/surge-synthesizer/surge-rack/actions/runs/4058875134/jobs/6986311302

and I didn't get this error

I wonder what it is that is making your system not define `__SSE_4_2__` at build time. To be sure are you using the latest rack SDK (2.2.3?)

I will give this a whirl on an actual linux box tomorrow. On my mac now and away from desk.

**Comment by qno** [comment] 2023-02-01 11:24
I added more OS variants in CI [here](https://github.com/qno/surge-rack/blob/build-native-ubuntus/.github/workflows/build-plugin.yml#L100)

```
  build-ubuntu-native:
    name: build-ubuntu-native
    needs: modify-plugin-version
    runs-on: ubuntu-latest
    container:
      image: ubuntu:${{ matrix.tag }}
      options: --user root
    strategy:
      fail-fast: false
      matrix:
        tag: [18.04, 20.04, 22.04, 23.04]
    steps:
      - name: Install Dependencies
        run: |
          apt update && apt install -y software-properties-common
          add-apt-repository ppa:git-core/ppa
          apt update && apt install -y jq build-essential git wget curl unzip zstd pkg-config
          wget https://github.com/Kitware/CMake/releases/download/v3.25.2/cmake-3.25.2-linux-x86_64.sh
          sh cmake-3.25.2-linux-x86_64.sh --prefix=/usr/local --skip-license
      - name: Dump infos
        run: |
          git --version
          cmake --version
          gcc --version
          g++ --version
          gcc -dM -E - < /dev/null
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/cache@v3
        id: plugin-version-cache
        with:
          path: plugin.json
          key: ${{ github.sha }}-${{ github.run_id }}
      - name: Get Rack-SDK
        run: |
          pushd $HOME
          curl -o Rack-SDK.zip https://vcvrack.com/downloads/Rack-SDK-${{ env.rack-sdk-version }}-lin-x64.zip
          unzip Rack-SDK.zip
      - name: Build plugin
        run: |
          export RACK_DIR=$HOME/Rack-SDK
          export VERBOSE=1
          make dep
          make dist
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: dist/*.vcvplugin
          name: linux-x64-ubuntu-${{ matrix.tag }}
```

Build result can be found [here](https://github.com/qno/surge-rack/actions/runs/4063742125/jobs/6996338262).
Looks like it is working with gcc version 9 and higher.

**Comment by baconpaul** [comment] 2023-02-01 11:39
yeah that seems correct and also shows @davidvivier 's original problem

hmm. i have some time on linux today. let me poke at one other thing.

@davidvivier I think some more specifics about OS, cmakeversion, compiler version, architecture etc... would help too.

**Comment by qno** [comment] 2023-02-01 11:50
To me it looks like he uses the latest surge-rack but an old Rack-SDK.

**Comment by qno** [comment] 2023-02-01 12:04
Proof is here - https://github.com/qno/surge-rack/actions/runs/4064062875/jobs/6997045410

Changed the SDK back to 2.2.1.

**Comment by baconpaul** [comment] 2023-02-01 12:08
And thanks @qno. I'll mark this issue as resolved and close it once we hear from david.

**Comment by davidvivier** [comment] 2023-02-01 13:59
thanks guys! i was using Rack 2.2.2 installed a few weeks ago ; i tried again with the recent 2.2.3 SDK but the same error occurs

```
[ 92%] Building CXX object CMakeFiles/plugin.dir/src/FX.cpp.o
In file included from /home/dave/Rack-SDK/dep/include/simde/x86/ssse3.h:30,
                 from /home/dave/Rack-SDK/dep/include/simde/x86/sse4.1.h:31,
                 from /home/dave/Rack-SDK/dep/include/simde/x86/sse4.2.h:31,
                 from /home/dave/Rack-SDK/include/simd/common.hpp:7,
                 from /home/dave/Rack-SDK/include/simd/Vector.hpp:3,
                 from /home/dave/Rack-SDK/include/simd/functions.hpp:2,
                 from /home/dave/Rack-SDK/include/dsp/common.hpp:4,
                 from /home/dave/Rack-SDK/include/rack.hpp:110,
                 from /home/dave/Rack-2.2.3/plugins/surge-rack/src/SurgeXT.h:18,
                 from /home/dave/Rack-2.2.3/plugins/surge-rack/src/FX.h:19:
/usr/lib/gcc/x86_64-linux-gnu/12/include/pmmintrin.h: At global scope:
/home/dave/Rack-SDK/dep/include/simde/x86/sse3.h:297:31: error: redefinition of ‘__m128 simde_mm_addsub_ps(__m128, __m128)’
  297 | #  define _mm_addsub_ps(a, b) simde_mm_addsub_ps(a, b)
      |                               ^~~~~~~~~~~~~~~~~~
/home/dave/Rack-SDK/dep/include/simde/x86/sse3.h:271:1: note: ‘simde__m128 simde_mm_addsub_ps(simde__m128, simde__m128)’ previously defined here
  271 | simde_mm_addsub_ps (simde__m128 a, simde__m128 b) {
      | ^~~~~~~~~~~~~~~~~~
```
If the fix you're talking about was already in 2.2.2 then it might be something else. I'm not sure if i can dig further.

However since i managed to load Surge modules natively into Rack (another installation, not in dev mode, so by adding the modules from the library), I don't need to compile them any more for now. So i wouldn't want you guys to spend more time on this if nobody else is impacted, you can close the ticket. Thanks!

**Comment by baconpaul** [comment] 2023-02-01 14:58
yeah i just did a fresh build 223 sdk linux no problem

My guess is either (1) you ahve some version wrong in the sdk somewhere or (2) you have an old glibc which isn't defining the symbol `__SSE_4_2__` properly?

I'm going to close this but I think the best advice I have is either do some upgrades (I'm about to push my box to 22.04 actually!) or alternately use the docker toolchain, an example of which you can see in `scripts/drun.sh`

**Closed by baconpaul** 2023-02-01 14:58 UTC
Labels: Resolved Awaiting User Confirm

**Comment by davidvivier** [comment] 2023-02-01 15:32
cmake 3.25.1 ; gcc 12.2.0 ; Linux Mint 19.3 ; `uname -a` outputs `Linux 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
