### ISSUE TITLE
EGxVCA 10 Seconds is not enough

### ISSUE THREAD

**Issue by martijndeluxe** [surge-synthesizer/surge-rack#832] opened 2023-02-07 10:51 UTC
The A D R times are limited to 10 seconds on the EGxVCA Module. In the Surge XT Synth these times go up to 32 seconds.

In my opinion 10 seconds  is really not enough from for say big gothic bells to electric piano's etc... I'm also a fan of long attack times for slow fade in chords and what not. I would not mind having more than 32 seconds for A D R say 1 minute. But 10 seconds from 0 to minus infinity is way to short...

Here's some real life examples of possible decay times. Attack times are from key down till peak level. Decay times are the time it takes to drop to -60 dB...

Fender Rhodes Low Note decay/release over 30 sec.
Steinway Piano Low Note decay/release over 50 sec.

Here are some popular old synth i measured some time ago...

DX7 max attack: 45 Sec, max decay/release 3.5 Min.
JX8P max attack: 40 Sec, max decay/release 2.5 Min.
Prophet5 max attack: 25 Sec, max decay/release 1 Min.

I hope this was the right place to put this comment.

Greetings,

-Martijn-

**Comment by Andreya-Autumn** [comment] 2023-02-07 12:17
It is the right place. :) And thanks for the input! 

And I agree, for what it's worth. I don't know when I'd ever use a >10s attack time personally, but  >30s decay is a given for piano-type envelopes. 

Maybe a "Long/Short" RMB option would be a good solution for this, since we don't wanna break existing patches now that this is in the library. This most likely won't get done very soon, because the focus is on another project right now. But it's a good suggestion, we'll think about it!

**Comment by baconpaul** [comment] 2023-02-07 13:30
An extended mode is a good idea 

the primary reason I chose 10 as the upper bound is to have enough throw distance on the sliders for tight envelopes. Adding an extended mode that takes them up to 100 wouldn’t be hard and we already have a ui idiom for it on other extendible controls.

**Comment by martijndeluxe** [comment] 2023-02-07 13:58
An Extended mode switch between max 10 and max 100 seconds for all 3 times Attack, Decay and Release sounds absolutely fantastic ;-)

-Martijn--

**Comment by baconpaul** [comment] 2023-02-07 15:39
And hold in DAHD mode! :)

I'll add a little '+' which does it for all the sliders when I get to it. I'm taking a tiny break from rack to work on another one of our portfolio projects this month but will return to this and some other 2.2 ideas soon enough. Thanks for suggesting it - its a good idea.

**Comment by baconpaul** [comment] 2023-02-09 01:48
Well good news @martijndeluxe - the other project we are embedded in required me to refactor and reuse some of the xt rack code so I started that today. Along the way that gave me the opportunity to add a 'slow' mode where the sliders all go from 0.05s -> 100s as opposed to 0.00039 -> 10

the next nightly build (https://github.com/surge-synthesizer/surge-rack/releases/tag/Nightly in about 20 minutes) will have this and the EGxVCA will have a 'fast slow' toggle in the top next to analog and digital toggle.

There's one more refactor I want to do but that will be end-user invisible so if you could give this a whirl that would be great. Its a useful enough change that if you think we got it right I could push a 2.1.2 version to the library also.

Thanks!

**Comment by baconpaul** [comment] 2023-02-09 02:26
Oh the display area LED is still not perfectly correct with the slow mode. That's on my list. but if you give it a whirl to check the DSP that'd be super

**Comment by martijndeluxe** [comment] 2023-02-09 09:21
Yippy ;-)

Super cool!!! One thing though... could in slow mode the minimum be 0.0039s instead of 0.05s? Than both minimum and maximum would be scaled by a factor 10...

4 ms would still be fast enough for attack for a bell with long decay...

Cheers!

**Comment by baconpaul** [comment] 2023-02-09 11:51
Sure it’s just slider throw sensitivity you sacrifice. I  can adjust that 

the display I need to do a tiny bit of work on. We actually run the envelope so a 400s envelope could be slow to compute so that’s why I need to do a touch of scaling work there

**Comment by baconpaul** [comment] 2023-02-09 12:00
Oh and just as a reminder to myself I need to make sure our phase calculation is accurate enough up to a 100 second slope but I will do that and remediate before I merge

**Comment by baconpaul** [comment] 2023-02-09 12:33
A 400s envelope would be the total runtime of an adsr with a d and r set to 100s. The problem is drawing the max length since the naive approach would have to run the lfo for 400*48000/8 loops to generate the 300 path points we need. So basically when I’m in slow mode I need to uniformly scale all the times down if the longest is longer than a few seconds to save graphics thread cpu

**Comment by baconpaul** [comment] 2023-02-09 15:00
OK I pushed a version which finishes my refactoring. I ended up setting the upper bound to 120 seconds since why not. And kept the lower bound the same. Makes the slow mode throw a bit finicky but the types all work also. Also did the thing to stop 8 minute envelopes grinding the UI to a halt. LOL.

New nightly in ~30 minutes. If you want to check it then I can close this issue and sometime next week get a 2.1.2 ready for the library.

**Comment by martijndeluxe** [comment] 2023-02-10 10:11
Just checked the nighty EGxVCA. Fantastic ;-) Thank you so much!!!
Greetings,
-Martijn-

**Comment by baconpaul** [comment] 2023-02-10 11:43
Great! I’ll close this issue when I submit it to the library probably early next week. One or two other tiny things to do first

**Closed** 2023-02-13 13:57 UTC
Labels: UI, Resolved Awaiting User Confirm

**Comment by baconpaul** [comment] 2023-02-19 14:22
This made it to the library today

**Comment by martijndeluxe** [comment] 2023-02-23 11:55
Works fantastic ;-)
Made a VCV Electric Piano Patch using only Surge Rack Modules.

https://www.what-sound.com/DATA/EPno.vcv

Could not have done it without the extended time range!!!

Cheers,
-Martijn-

**Comment by baconpaul** [comment] 2023-02-23 13:04
Awesome!

2.1.4 will have a few more egxvca fixes for pan - all super useful because of feedback exactly like yours. Thanks for highlighting the need!
