### ISSUE TITLE
Delay module insertion causes Rack 2.4.1 to crash

### ISSUE THREAD

**Issue by dowdm** [surge-synthesizer/surge-rack#932] opened 2023-09-08 05:51 UTC
Rack 2.4.1  Crashes when loading delay module from library bowser: (Win 11)
1. Open library
2. Select delay module
3. Par-tay

100% repeatable in existing patch, not sure if it occurs in blank patch.

VCV Log attached:
[log.txt](https://github.com/surge-synthesizer/surge-rack/files/12555926/log.txt)

**Comment by Andreya-Autumn** [comment] 2023-09-08 07:49
Thanks for the report. Can't confirm here on MacOS, so probably platform specific. 

And this started happening after upgrading rack to 2.4.1 I gather? It wasn't in 2.3? Are any of our other modules doing the same thing, or just the delay?

**Comment by dowdm** [comment] 2023-09-08 10:46
I actually never tried it in 2.3, so  I'm not sure. Chorus and Ensemble are working just fine. I haven't tried many of the other modules for issues.

**Comment by Andreya-Autumn** [comment] 2023-09-08 11:24
Alright thanks. If any of the other ones cause the crash as well, let us know. 

Did you get a system crash log as well by any chance?

**Comment by baconpaul** [comment] 2023-09-08 11:56
The rack log.txt will include crash reports most systems. Can you attach one from a crash? It will be in your rack2 docs directory called log.txt

Are you running from the library or the nightly?

Also finally we have 3 delay modules. It is just the one called delay right?

thanks

**Comment by dowdm** [comment] 2023-09-08 12:21
The log.txt should be attached to the original post. It is the module just called "delay". The module is from the rack library, however my other formats of surge xt are nightly. I don't know if the modules reference anything in that.

**Comment by baconpaul** [comment] 2023-09-08 12:26
Sorry still pre-coffee here. Very useful.

And wow right so crazy, this is the same error Jacky had with starting surge modules in some cases. It is throwing an error reading your documents directory for a preset scan. I'm not sure why and we could never find out but I did fix it.

So in the nightly (which will be 2.2 this fall) this was solved for him. Would you mind downloading and checking that? You can get it [here](https://github.com/surge-synthesizer/surge-rack/releases/tag/Nightly)

**Comment by dowdm** [comment] 2023-09-08 12:29
Awesome - it'll probably be a couple days before I get around to testing that out. Will report back

**Comment by Petervos2018** [comment] 2023-09-08 12:52
Hi Paul
I was just testing this and found that on win 10 I have 2 surge folders, the old one and the XT one.
As seen here : 
![afbeelding](https://github.com/surge-synthesizer/surge-rack/assets/46076474/30999566-3447-4b6b-a317-0fd43920493f)
They both have Presets folders but they are inside the plugins folder.
When I try to load one of them, I have to browse to the right folder , find the file and click load, it will crash Rack 2.4.1.
The standard presets seen here : 
![afbeelding](https://github.com/surge-synthesizer/surge-rack/assets/46076474/57bca2d1-ccc1-475f-a435-7fe950029634)
work fine. 
( but I can not find them on the harddisk (I guess they are internal))

Greetings Peter.

**Comment by Andreya-Autumn** [comment] 2023-09-08 13:08
That might be a clue yeah. In the VST we use the same file format for the old and new version, and loading old patches in XT pops a warning screen but mostly works. Not so in Rack apparently. Thanks for reporting!

**Comment by baconpaul** [comment] 2023-09-08 13:27
SurgeRack is the pre-XT stuff. Totally separate.
The error here is scanning the surge-itself-as-vst not rack folder. That is, it is looking in %DOCUMENTS%/Surge XT/FXPresets since it inherits the code from the VST3

For some reason that throws a filesystem exception for some folks, but that exception was uncaught

In 2.2, I both catch that exception and report it to the log rather than to the os.

You can safely delete the SurgeRack folder *if* you only have the SurgeXT plugins. The Surge plugins themselves are all hidden and we just keep them around for patch compat.

**Comment by Petervos2018** [comment] 2023-09-08 16:56
I know SurgeRack is the "old" version and it's replaced by SurgeXTRack. I was saying that loading a preset from the Presets folder within The plugins folder I mean one of these : 

![afbeelding](https://github.com/surge-synthesizer/surge-rack/assets/46076474/12a1e205-8b3c-4ad5-887f-a8f20a542a8c)

into (in this case) Rotary will result in Rack closing.
Is this (also) what you mean ?

**Comment by Andreya-Autumn** [comment] 2023-09-08 19:19
Yeah we understood you. And the attempt to load that file causing the crash is expected. 

As Paul said, if you have no reason to keep that folder around (and the only reason would be if you have the old surge modules in old projects), you can safely delete it, preventing the problem. 

Also as Paul said earlier, the latest nightly (and upcoming 2.2 release) almost certainly has this fixed. So if you can download and run the nightly and verify that that prevents the crash, that's appreciated. Assuming it fixes it for you and OP, we can close this issue. :)

**Comment by Petervos2018** [comment] 2023-09-08 19:42
I'm just thick, I don't understand what is going on I already installed the latest nightly, and that was the one crashing rack when II tried to load the the "old" preset from the "SurgeXTRack" not the even older "SurgeRack" into one of the modules.
As you can see the presets are from the 5th of september 2023 and are probably extracted from the nightly vcvplugin. So you are saying ~~is give peace a chance~~ I can delete the "SurgeRack" folder or the presets folder in "SurgeXTRack" ? or is that preset folder used by the now hidden SurgeRack modules ? and will create a crash when I try to load them into the XT version.

Love you,
Petrer.

**Comment by baconpaul** [comment] 2023-09-08 21:18
All I was saying is: the stack in the log at the top of this stack is not from reading any of those presets

**Comment by Andreya-Autumn** [comment] 2023-09-08 21:23
Yeah maybe I was the thick one, I didn't pay full attention to the path in your screenshot. Sorry. 

But I can confirm that problem actually. And will open a separate issue for it, since it seems like a separate problem.

**Comment by baconpaul** [comment] 2023-09-08 21:24
Thanks both!

**Comment by Andreya-Autumn** [comment] 2023-09-08 21:32
#933

**Comment by dowdm** [comment] 2023-09-09 01:53
So the 2.2 beta nightly works with delay  module loading. 

There seem to be 2 preset locations (on win) and perhaps it's looking in the wrong place at load: 
C:\Users\theof\Documents\Rack2\presets\SurgeXTRack\SurgeXTDelay and
C:\Users\theof\Documents\Rack2\plugins-win-x64\SurgeXTRack\presets\SurgeDelay

Also my entire folder is cloud backup enabled - I know that can sometimes cause location issues.

**Comment by Andreya-Autumn** [comment] 2023-09-09 09:01
Yeah, leave the second path alone, that's the one mentioned in #933, those presets will crash you (because they're not made for the current modules). We won't ship them in 2.2

Anyway, glad to hear the nightly fixed it for you! Closing as completed.

**Closed by Andreya-Autumn** 2023-09-09 09:01 UTC
Labels: Infrastructure, Resolved Awaiting User Confirm
