### ISSUE TITLE
LFOxEG - Outputs in Wrong Order - Maybe?

### ISSUE THREAD

**Issue by therealkitman** [surge-synthesizer/surge-rack#851] opened 2023-02-21 07:27 UTC
If I put this plugin in Envelope mode only and Deform the waveform to give a curve shape to the EG, I would have assumed the EG output would have this curve. But only the LFO and LFOxEG outputs display the curve as in the plugin display.

Should the EG output reflect this curve as well? Or maybe I'm misinterpreting the plugin display and the shadow of the envelope.

![image](https://user-images.githubusercontent.com/14888092/220274863-16cc7441-f8d2-4019-b8dd-4b49c8e48e6b.png)

**Comment by Andreya-Autumn** [comment] 2023-02-21 12:00
Interesting! In Surge proper all three outputs respond to the deform param in envelope mode, but the display does not show this for the EG-only output. These could be related or totally separate issues I guess. 

Anyway. Deform doesn't impact the EG in any of the other modes, which is intended. But I agree it'd make sense to make an exception for envelope mode. Thanks for the report!

**Comment by baconpaul** [comment] 2023-02-22 01:38
There's a couple of reasons I did it this way

1. Deform doesn't impact EG in any of the other modes and you can get the deformed and non-deformed version out
2. In legato modes with some deform modes it is very hard to get a continuous deformed envelope so we do a little smoothing on retrigger which means sometimes you want the undeformed envelope in that case

So other than the fact that the UI doesn't show the undeformed envelope - which might be an issue - I don't think there's a DSP or output problem here. 

Thoughts welcome.

**Comment by baconpaul** [comment] 2023-02-22 01:42
Hmm and the display even does the right thing.

Is it the problem that the LFO output isn't just pinned at 1 (so LFO x EG != lfo x eg?)

**Comment by therealkitman** [comment] 2023-02-22 05:53
I woke up this morning and the first thing on my mind was this plugin :laughing: I'm thinking that the outputs are right as @baconpaul mentions above.

In the Type:Envelope the Waveform controls - Deform - shapes a 'blank' LFO with just the envelope trace. This is what we see at the output of LFO. Therefore the EG output is right too - plain envelope trace as set by the DAHDSR controls only.

The LFOxEG would be obviously the combo, which it is.

I keep treating the LFOxEG as a VCAxEG or QUAD LFO - which it isn't. 

I'd be OK if you want to close this.

**Comment by baconpaul** [comment] 2023-02-22 11:35
Yeah I think I would leave the outputs but perhaps bulk up the manual. The lfo output in env mode has the env in it - will leave this open until I can figure out what to say :)

**Comment by Andreya-Autumn** [comment] 2023-02-23 17:38
Just updated the manual to make current intended behaviors clear. Other improvements TBD, closing this and opening another issue for those. Thanks!

**Closed by Andreya-Autumn** 2023-02-23 17:38 UTC
Labels: DSP etc, surge underlying bug
