### ISSUE TITLE
Selecting PatchPlayer from module browser crashes Rack

### ISSUE THREAD

**Issue by SteveRussell33** [surge-synthesizer/surge-rack#216] opened 2019-06-14 17:32 UTC
From log.txt
[14.296 info src/SurgeModuleCommon.hpp:87] [SurgeRack] Instance: Module=PatchPlayer BuildInfo=os:win pluggit:7b7a0b4 surgegit:2ed1513 buildtime=Jun 14 2019 15:25:57
[14.343 info src/SurgeModuleCommon.cpp:98] [SurgeRack] SurgeStorage::dataPath = ./plugins-v1/SurgeRack/surge-data/
[14.343 info src/SurgeModuleCommon.cpp:99]             SurgeStorage::userDataPath = 
[14.343 info src/SurgeModuleCommon.cpp:100]             SurgeStorage::wt_list.size() = 307
[14.343 warn src/UserInteractionsRack.cpp:14] Surge Error
Surge is not properly installed.
Cannot find 'configuration.xml' in path ''. Please reinstall surge.

[14.343 warn src/UserInteractionsRack.cpp:14] Surge Error
Surge Installation Error
Surge was unable to load wavetables from ''. The directory contains no wavetables. Please reinstall using the Surge installer.

[14.359 warn src/UserInteractionsRack.cpp:14] Surge Error
Surge Installation Error
Surge was unable to load factory patches from ''. Surge found 0 factory patches. Please reinstall using the Surge installer.

Rack v1.dev.6b6c852
SurgeRack-1.beta1.7b7a0b4

As this is a Release beta build zip that I'm using the surge-data dir is under plugins-v1/SurgeRack (we discussed this before in the other issue - the neater option I think) so I can't see why this is failing as the data is all there. 

Path error in src/SurgeModuleCommon.cpp?

**Comment by baconpaul** [comment] 2019-06-14 17:39
Does plugins-v1/SurgeRack/surge-data/configuration.xml exist? What is the contents of plugins-v1/SurgeRack/?

**Comment by baconpaul** [comment] 2019-06-14 17:40
Oh damnit no I know exactly what the problem is. Hold on. Patch coming.

**Comment by baconpaul** [comment] 2019-06-14 17:41
(SurgePatchPlayer uses a different startup path for storage and will require special treatment)

**Comment by baconpaul** [comment] 2019-06-14 17:53
Ahh and the reason it works for me is because I have the VST installed, which installs in a default location, so I am reading assets from the VST install by accident.

Thank you. This is a very valuable bug report. I have a fix coming together now.

**Comment by baconpaul** [comment] 2019-06-14 18:21
Alright I was able to replicate this by uninstalling my system wide surge VST assets and running it; immediate crash. And I was able to fix it by threading the appropriate path through the different constructor path that is needed for this module. I saw the crash resolved so I pushed it

f7a75e8 

a release with that commit will work. The release on the releases/ page now contains it. So if you could re-download and try again and if it works, close this issue, I would greatly appreciate it.

And thank you. That is two super useful bugs you have found which my system masked. Appreciate your patience and accuracy in reporting them.

**Comment by SteveRussell33** [comment] 2019-06-14 19:02
No problem Paul glad to help! 

I have the VST as well, didn't occur to me that might be a problem your end.

**Closed** 2019-06-14 19:10 UTC

**Comment by baconpaul** [comment] 2019-06-14 19:13
Fantastic! Thank you. 

Most problems with surge-rack are a problem on my end :)  30 seconds after I read the log I knew exactly the problem and slapped my forehead. Appreciate it.

Also enjoy the module! If you combine it with the PolyGenerator from the latest BaconMusic you can get some very nice results...

**Comment by SteveRussell33** [comment] 2019-06-14 19:17
You're very welcome.

Thanks for the module tip! Will try that out.

**Comment by baconpaul** [comment] 2019-06-14 19:18
Yup. The more natural approach is midi to it with v/oct to note, vel to vel and gate to gate. That lets you play surge in rack immediately basically.
